name : generate data.json other files
on : push

jobs:
  build:
    name : generate
    runs-on: ubuntu-latest
    steps:
      - name: checkout and build
        uses: actions/checkout@v2
        run: |
          IMAGE_NAME=covid19-aichi-tools:${GITHUB_REF#refs/heads/}
          docker build . --${GITHUB_REPOSITORY}/${IMAGE_NAME}        
