name : generate data.json other files
on : push

jobs:
  build:
    name : generate
    runs-on: ubuntu-latest
    steps:
      - name : setup
        uses : actions/docker/cli@master
        with :
          args : build --tag=repo:latest .
