name : generate data.json other files
on : push

jobs:
  build:
    name : generate
    steps:
      - name : setup
        uses : actions/docker/cli
        args : 
          - build --tag=repo:latest .
